BEGIN;
    INSERT INTO course_students VALUES (1, 11);
    INSERT INTO course_students VALUES (2, 12);
    INSERT INTO course_students VALUES (5, 13);
    INSERT INTO course_students VALUES (4, 14);
    INSERT INTO course_students VALUES (3, 15);
    INSERT INTO course_students VALUES (1, 16);
    INSERT INTO course_students VALUES (2, 17);
    INSERT INTO course_students VALUES (4, 18);
    INSERT INTO course_students VALUES (5, 19);
    INSERT INTO course_students VALUES (1, 20);
COMMIT;